import type { LearnerLevel } from '../../constants';
import type { Domain } from './types';

const CXR_TIP = '*Tip: In radiology, images are flipped like you\'re facing the patient. Left side of the image = patient\'s right. When you describe a finding to the AI, that description is called a **prompt**. A precise prompt gets a better response. For example: "opacity in the patient\'s right lower lobe" is a stronger prompt than "the white area."*';

const CT_TIP = '*Tip: On CT, bright white = dense (blood, bone, contrast). Dark = air or fluid. Unlike X-rays, CT images are NOT flipped, so left on the screen is the patient\'s left. When you describe a finding to the AI, that description is called a **prompt**. A precise prompt gets a better response. For example: "hyperdense collection in the left epidural space with midline shift" is a stronger prompt than "the white area."*';

const MRI_TIP = '*Tip: In radiology, images are flipped like you\'re facing the patient. Left side of the image = patient\'s right. When you describe a finding to the AI, that description is called a **prompt**. A precise prompt gets a better response. For example: "patient\'s right lateral ventricle" is a stronger prompt than "the right side."*';

const SUGGESTIONS_NO_IMAGE: Record<LearnerLevel, string[]> = {
  highschool: ["What is MRI?", "What can brain scans show us?"],
  undergrad: ["What are the different MRI sequences and why do we use them?", "What should I know about this patient's history before looking at the images?"],
  ms_preclinical: ["Walk me through the anatomy I should know for this case.", "What sequences should I look at first and what does each one show?"],
  ms_clinical: ["Walk me through how to approach this case systematically.", "Given the clinical history, what is my differential before looking at imaging?"],
  resident: ["Given AFib and memory decline, what findings am I looking for?", "How do I distinguish chronic from acute infarct on MRI?"],
};

const SUGGESTIONS_WITH_IMAGE: Record<LearnerLevel, string[]> = {
  highschool: ["What am I looking at in this brain scan?", "Is anything unusual here?"],
  undergrad: ["What structures can I identify on this slice?", "What should look different if something is wrong?"],
  ms_preclinical: ["What anatomy do I see on this slice?", "What is the pathophysiology behind this finding?"],
  ms_clinical: ["What findings do I see and what is my differential?", "How does this sequence help me distinguish acute from chronic?"],
  resident: ["I think I see a finding — let me describe it.", "Compare this slice across sequences for me."],
};

const CXR_SUGGESTIONS_NO_IMAGE: Record<LearnerLevel, string[]> = {
  highschool: ["What does a normal chest X-ray look like?", "How do doctors read X-rays?"],
  undergrad: ["What is the systematic approach to reading a chest X-ray?", "How do I tell the left side from the right?"],
  ms_preclinical: ["What anatomy should I identify on a CXR?", "Explain the silhouette sign and how it localizes findings."],
  ms_clinical: ["Walk me through the ABCDE approach to this CXR.", "What findings should I look for given the clinical history?"],
  resident: ["What is my differential based on the clinical presentation?", "How do I integrate the imaging with the exam findings?"],
};

const CXR_SUGGESTIONS_WITH_IMAGE: Record<LearnerLevel, string[]> = {
  highschool: ["Does one side look different from the other?", "What could cause this white area?"],
  undergrad: ["What abnormality do I see and which side is it on?", "Is the heart or trachea shifted?"],
  ms_preclinical: ["What is the silhouette sign and how does it help here?", "What is the pathophysiology behind this finding?"],
  ms_clinical: ["Let me describe the findings I see on this CXR.", "What is my management plan based on these findings?"],
  resident: ["I want to present this case as if at morning report.", "What is my management plan based on these findings?"],
};

function isCxrLikeCase(studyId?: string): boolean {
  return !!studyId && (studyId.startsWith('cxr-') || studyId.startsWith('axr-') || studyId.startsWith('ct-') || studyId.startsWith('xr-'));
}

const CXR_WELCOME_MESSAGES: Record<string, Record<LearnerLevel, string>> = {
  'cxr-pneumothorax': {
    highschool: `**A 21-year-old man came to the emergency room because he suddenly felt a sharp pain in his chest and had trouble breathing.**\n\nAn X-ray is a type of medical image that uses a small amount of radiation to take a picture of the inside of your body. On a chest X-ray, bones appear bright white, air appears black, and soft tissues appear in shades of gray. The lungs are normally filled with air, so they look dark on both sides of the chest.\n\n*Tip: You can ask me to explain anything in simpler terms. Try saying "What does that mean?" whenever something is unclear.*\n\nTake a close look at the image. Compare the left side and the right side of the chest.\n\n**Can you spot any difference between the left side and the right side of the image?**`,
    undergrad: `**A 21-year-old male presents to the ED with acute-onset left-sided chest pain and dyspnea. No prior medical history. A PA chest radiograph was obtained.**\n\nOn a normal chest X-ray, both lung fields should appear symmetrically dark because they are filled with air. You should see branching pulmonary vessels extending from the hila toward the periphery. The mediastinum (containing the heart, great vessels, trachea, and esophagus) should be roughly midline.\n\n*Tip: Describe exactly what you see before jumping to a diagnosis. Saying "I notice X on the left but not on the right" trains your observational skills.*\n\nLook carefully at both lung fields. Pay attention to lung markings, the position of the heart and trachea, and any asymmetry.\n\n**What differences do you notice between the left and right hemithoraces?**`,
    ms_preclinical: `**A 21-year-old male with no significant PMH presents to the ED with sudden-onset left-sided pleuritic chest pain and progressive dyspnea. He is tall and thin (BMI 19). Vitals: HR 118, BP 102/68, RR 28, SpO2 91% on room air. Breath sounds markedly diminished on the left. Trachea may be deviated. A PA chest radiograph was obtained.**\n\n*Tip: Build your differential first, then use the imaging to narrow it.*\n\nSudden pleuritic pain, tachycardia, hypoxia, unilateral diminished breath sounds in a young, tall, thin male — the vignette itself is a clue before you look at the image.\n\n**Describe what you see on the CXR. Focus on lung markings, mediastinal position, and any asymmetry between the two hemithoraces.**`,
    ms_clinical: `**A 21-year-old male with no significant PMH presents to the ED with sudden-onset left-sided pleuritic chest pain and progressive dyspnea. He is tall and thin (BMI 19). Vitals: HR 118, BP 102/68, RR 28, SpO2 91% on room air. Breath sounds markedly diminished on the left. Trachea may be deviated. A PA chest radiograph was obtained.**\n\n*Tip: Build your differential first, then use the imaging to narrow it.*\n\nSudden pleuritic pain, tachycardia, hypoxia, unilateral diminished breath sounds in a young, tall, thin male.\n\n**What are your top three differentials before you look at the image? Then read the CXR and tell me which one the imaging supports.**`,
    resident: `**EMS brings in a 21-year-old male, no PMH, in moderate-to-severe respiratory distress. Onset 2 hours prior. Tall, asthenic habitus (6'2", 145 lbs). Vitals: HR 124, BP 94/62, RR 32, SpO2 88% on 15L NRB. JVD present. Trachea deviated right. Left hemithorax hyperresonant. Breath sounds absent left. A portable PA chest radiograph was obtained.**\n\nNote: In a real scenario with these vitals and exam findings, obtaining imaging before decompression would be a management error. This X-ray is available for educational purposes only.\n\n*Tip: Walk me through your decision-making in real time. I will push back if your reasoning has a gap.*\n\n**Is this a needle-decompression-first or chest-tube-first scenario? Walk me through your ATLS algorithm, including anatomical landmarks. ATLS 10th edition changed the primary needle decompression site to 4th/5th ICS at the AAL; how does this compare to the traditional 2nd ICS MCL?**`,
  },
  'cxr-pneumonia': {
    highschool: `**Case: 67-year-old man with a bad cough and fever.**\n\nFor the past 3 days he has had a cough that brings up thick yellow-green mucus, a temperature of 101.5 F, and chills. His doctor ordered a chest X-ray.\n\n*Tip: Be specific when describing what you see. "White area in the right lung" is a stronger description than "something looks wrong."*\n\nYou are looking at a chest X-ray. Healthy lungs should look mostly dark because they are full of air. Bones look white. The heart sits in the middle.\n\nLook at both lungs. Does one side look different from the other? Is there an area that looks whiter or cloudier than the rest?\n\n**What do you think happens to the lungs when someone gets pneumonia?**`,
    undergrad: `**Case: 67-year-old male, productive cough and fever x 3 days.**\n\nPresenting with purulent sputum, fever (38.6 C / 101.5 F), and rigors. Former smoker with COPD. Nasopharyngeal culture grew Moraxella catarrhalis. PA chest X-ray obtained.\n\n*Tip: "Dense opacity in the right middle lung zone with a sharp inferior border" is more useful than "something white on the right."*\n\nYou are viewing a PA chest X-ray. The lungs have 5 lobes: 3 on the right (upper, middle, lower) and 2 on the left (upper, lower). On a frontal view the lobes overlap, but certain signs help localize findings.\n\nCompare the density of right and left lungs. Pay attention to whether any area looks opacified and whether the heart border or diaphragm outline is affected.\n\n**What is the difference between consolidation and atelectasis, and how might you tell them apart on this X-ray?**`,
    ms_preclinical: `**Case: 67M, productive cough, fever, rigors x 3 days.**\n\nPMH: COPD, 30 pack-year history (quit 5 years ago). Vitals: T 38.6 C, HR 98, BP 135/82, RR 22, SpO2 93% RA. Exam: decreased breath sounds and bronchial breathing over right anterior chest; dullness to percussion. WBC 15,200 with left shift. NP culture: Moraxella catarrhalis. PA CXR obtained.\n\n*Tip: Use radiologic language. "Dense opacity obscuring the right heart border" gets a more precise teaching response.*\n\nSystematic approach: (1) Technical quality. (2) Mediastinal contours and hilae. (3) Each lung zone. (4) Costophrenic angles and retrocardiac space. (5) Bones and soft tissues.\n\nFocus on the right lung. Identify the abnormality and determine which lobe is involved using the silhouette sign.\n\n**What is the silhouette sign and how does it help you localize this finding? What is the pathophysiology of lobar consolidation, and what are the 4 classic histologic stages?**`,
    ms_clinical: `**Case: 67M, productive cough, fever, rigors x 3 days.**\n\nPMH: COPD, 30 pack-year history (quit 5 years ago). Vitals: T 38.6 C, HR 98, BP 135/82, RR 22, SpO2 93% RA. Exam: decreased breath sounds and bronchial breathing over right anterior chest; dullness to percussion. WBC 15,200 with left shift. NP culture: Moraxella catarrhalis. PA CXR obtained.\n\n*Tip: Use radiologic language. "Dense opacity obscuring the right heart border" gets a more precise teaching response.*\n\nIdentify the finding, localize it, then shift to management.\n\n**Based on age, comorbidities, and the cultured organism, would you classify this as "typical" or "atypical" pneumonia? Calculate the CURB-65 score. What is your empiric antibiotic regimen per ATS/IDSA guidelines?**`,
    resident: `**Case: 67M, ED presentation. CC: productive cough, fever, dyspnea x 3 days.**\n\nPMH: COPD (FEV1 55%), 30 pack-year (quit 5 yrs), HTN, pre-diabetes. Vitals: T 38.6 C, HR 98, BP 135/82, RR 22, SpO2 93% RA. Exam: bronchial breath sounds RML, egophony, dullness to percussion. Labs: WBC 15.2 (left shift), procalcitonin 2.4 ng/mL. Sputum Gram stain: gram-negative diplococci. NP culture: Moraxella catarrhalis. PA CXR obtained.\n\n*Tip: Frame questions like an oral board case. The AI will respond at attending-level depth.*\n\nAfter your interpretation, work through: (1) CURB-65 and PSI/PORT score. (2) Disposition. (3) Empiric antibiotics per ATS/IDSA 2019 guidelines. (4) Parapneumonic effusion risk. (5) Treatment failure criteria.\n\n**Given Moraxella catarrhalis (a universal beta-lactamase producer), how does this affect your empiric regimen? When would you de-escalate to targeted therapy?**`,
  },
  'cxr-chf': {
    highschool: `**Welcome to your case.**\n\n**A 68-year-old man comes to the emergency room because he cannot catch his breath. Over the past few days his breathing has gotten worse, especially when he lies down. He has had to sleep sitting up.**\n\nThe heart is a pump. When it becomes too weak to pump effectively, blood backs up into the lungs like a traffic jam. Fluid leaks into the air sacs, making it very hard to breathe.\n\n*Tip: You can ask me to explain anything in simpler terms. There are no wrong questions.*\n\nOn a normal X-ray, the lungs should look mostly dark because they are full of air. The heart sits in the middle as a white shape.\n\n**Can you see anything different about the size of the heart? And do the lungs look clear and dark, or hazy and white?**`,
    undergrad: `**Welcome to your case.**\n\n**A 68-year-old male with hypertension and type 2 diabetes presents with progressive dyspnea over 5 days, orthopnea, and bilateral lower extremity edema. Last night he experienced paroxysmal nocturnal dyspnea. Vitals: HR 110, BP 168/94, RR 28, SpO2 89% RA. PA chest radiograph obtained.**\n\n*Tip: Be specific. "The blood vessels at the top of the lungs look bigger than the ones at the bottom" is much more useful than "something looks weird."*\n\nNormally, blood flow follows gravity: in an upright patient, vessels at the bases are larger than those at the apices. When the left ventricle fails, pressure builds in the pulmonary veins and fluid leaks into the tissue.\n\nLook at the heart size, upper vs. lower lung vessels, and the costophrenic angles.\n\n**What do you notice about the relative size of blood vessels at the top vs. bottom of the lungs? What could cause this reversal?**`,
    ms_preclinical: `**Welcome to your case.**\n\n**A 68-year-old male with PMH of HTN, T2DM, and known HFrEF (EF 30%) presents with 5 days of progressive dyspnea, now dyspneic at rest. 3-pillow orthopnea, 2 episodes of PND this week. Ran out of furosemide 10 days ago. Exam: JVD, bibasilar crackles, S3 gallop, 2+ pitting edema. Vitals: HR 110, BP 168/94, RR 28, SpO2 89% RA. BNP 1,840 pg/mL. PA CXR obtained.**\n\n*Tip: Describe every finding before synthesizing. Use the ABCDE mnemonic: Alveolar edema, Kerley B lines, Cardiomegaly, Dilated upper lobe vessels, Effusions.*\n\nThis case is high-yield for Starling forces and the pathophysiology of pulmonary edema.\n\n**Walk me through every radiographic finding you can identify. Then explain the pathophysiologic sequence: how does elevated LVEDP lead to each finding you see on the CXR?**`,
    ms_clinical: `**Welcome to your case.**\n\n**A 68-year-old male with PMH of HTN, T2DM, and known HFrEF (EF 30%) presents with 5 days of progressive dyspnea, now dyspneic at rest. 3-pillow orthopnea, 2 episodes of PND this week. Ran out of furosemide 10 days ago. Exam: JVD, bibasilar crackles, S3 gallop, 2+ pitting edema. Vitals: HR 110, BP 168/94, RR 28, SpO2 89% RA. BNP 1,840 pg/mL. PA CXR obtained.**\n\n*Tip: Describe every finding before synthesizing. Use the ABCDE mnemonic: Alveolar edema, Kerley B lines, Cardiomegaly, Dilated upper lobe vessels, Effusions.*\n\nIdentify the findings, then shift to acute management.\n\n**What is the BNP telling you and how does it fit the clinical picture? Walk me through your initial management: oxygen strategy, diuretic regimen, and when you would consider NIPPV vs. intubation.**`,
    resident: `**Welcome to your case.**\n\n**A 68-year-old male with HFrEF (EF 30%, ischemic CMP s/p LAD stent), HTN, T2DM, CKD 3a, AFib (rate-controlled on metoprolol) presents via EMS in acute respiratory distress. Ran out of furosemide 10 days ago. Vitals: HR 118 (irreg irreg), BP 178/102, RR 32, SpO2 85% on 15L NRB. BNP 1,840. Bedside echo: EF 20-25%, moderate MR, RVSP 55. PA CXR obtained.**\n\nNIPPV has Class IIa evidence (not Class I) for reducing intubation rates per 2022 AHA/ACC guidelines.\n\n*Tip: Treat this like oral boards. Walk me through your first 30 minutes.*\n\nClassify this patient's Stevenson profile (Wet = PCWP >= 18; Cold = CI < 2.2 L/min/m2).\n\n**What is this patient's Stevenson profile? Walk me through your acute management: oxygen strategy, IV diuretic regimen, vasodilator candidacy, and your threshold for inotropic support.**`,
  },
  'cxr-effusion': {
    highschool: `**Welcome to your case.**\n\n**A 58-year-old man comes to the emergency room because he can barely breathe. He has been getting more and more short of breath over the past three weeks, and now he can only walk a few steps. He has also lost 15 pounds without trying.**\n\n*Tip: You can ask me anything. If I use a word you do not know, just say "what does that mean?"*\n\nA normal chest X-ray should look mostly dark on both sides, because the lungs are full of air.\n\nNotice that one side of this X-ray looks completely different from the other. One side is almost entirely white.\n\n**Which side looks abnormal, and what do you think might be filling that space to make it white instead of black?**`,
    undergrad: `**Welcome to your case.**\n\n**A 58-year-old male presents with 3 weeks of progressive dyspnea on exertion, now dyspneic at rest. He reports 15-pound unintentional weight loss over 2 months. 40-pack-year smoking history. Vitals: HR 105, RR 24, SpO2 91% RA. Breath sounds absent over the entire left hemithorax. PA chest radiograph obtained.**\n\n*Tip: Describe what you see in your own words before asking me to explain.*\n\nRemember the pleural space: the thin potential space between the visceral pleura (covering the lung) and the parietal pleura (lining the chest wall). Normally it contains only a few milliliters of fluid.\n\n**One hemithorax is completely opacified. What could accumulate in the pleural space to cause this, and can you think of reasons the fluid might be protein-poor (transudate) versus protein-rich (exudate)?**`,
    ms_preclinical: `**Welcome to your case.**\n\n**A 58-year-old male with a 40-pack-year smoking history presents with progressive dyspnea over 3 weeks. 15-pound weight loss, nonproductive cough, dull left chest pain. Vitals: T 37.2C, HR 105, BP 128/82, RR 24, SpO2 91% RA. Exam: tracheal deviation to the right, absent breath sounds and dullness to percussion over the entire left hemithorax, decreased tactile fremitus. PA CXR obtained.**\n\n*Tip: Talk through your reasoning. Do not just name the finding; tell me WHY.*\n\nRead systematically: airway, bones, cardiac silhouette, diaphragm, everything else.\n\n**Describe the radiographic findings. What is the anatomy of the pleural space, and what pathophysiologic mechanisms cause fluid to accumulate there? Walk me through Light's criteria: the three parameters and their cutoffs.**`,
    ms_clinical: `**Welcome to your case.**\n\n**A 58-year-old male with a 40-pack-year smoking history presents with progressive dyspnea over 3 weeks. 15-pound weight loss, nonproductive cough, dull left chest pain. Vitals: T 37.2C, HR 105, BP 128/82, RR 24, SpO2 91% RA. Exam: tracheal deviation to the right, absent breath sounds and dullness to percussion over the entire left hemithorax, decreased tactile fremitus. PA CXR obtained.**\n\n*Tip: Talk through your reasoning. Do not just name the finding; tell me what it changes about management.*\n\nIdentify the findings, classify the effusion, then plan your workup.\n\n**Given the smoking history and weight loss, what is at the top of your differential? After confirming a large pleural effusion, what are the next diagnostic steps and how would the fluid analysis guide your management?**`,
    resident: `**Welcome to your case.**\n\n**A 58-year-old male with NSCLC (left upper lobe adenocarcinoma, stage IVA, EGFR wild-type, PD-L1 TPS 60%) presents with progressive dyspnea despite 4L O2 at home. Completed cycle 1 of carboplatin/pemetrexed plus pembrolizumab 3 weeks ago. Pleural fluid: LDH 340 (serum 220), protein 5.8 (serum 7.2), glucose 45, pH 7.28. Prior cytology: adenocarcinoma cells. PA CXR obtained.**\n\n*Tip: I will challenge your management decisions. Defend your plan and anticipate complications.*\n\nTalc pleurodesis success rate is approximately 80-95% in published series (not 70-80%). For asymptomatic MPE, the ATS guideline recommends observation only.\n\n**This patient has a known malignant effusion with symptomatic recurrence. What are your management options (large-volume thoracentesis vs. pleurodesis vs. IPC), and what factors in this patient influence your choice?**`,
  },
  'axr-sbo': {
    highschool: `**A 45-year-old woman comes to the emergency room with terrible belly pain. For the last 2 days, her stomach has been getting more and more swollen and painful. She has been throwing up and has not been able to go to the bathroom.**\n\nShe had her appendix removed a few years ago. Scar tissue from that surgery may be causing a problem inside.\n\n*Tip: You can ask me to explain anything. Just say "what does that mean?" if I use a word you don't know.*\n\nYou are looking at an X-ray of her abdomen (belly area) taken while she was standing up. On an X-ray, gas looks black and bones look white.\n\nLook at the middle of the image. Do you see any areas that look like swollen tubes? Can you spot the flat, straight lines where dark (gas) meets lighter gray (fluid)?\n\n**What do you think happens inside your body when the intestine gets blocked?**`,
    undergrad: `**A 45-year-old female presents with 2 days of progressive crampy abdominal pain, distension, nausea, and vomiting. No flatus for 24 hours. PMH: appendectomy 5 years ago. Vitals: HR 105, BP 118/76. Abdomen is distended and tympanitic with high-pitched bowel sounds. Upright abdominal radiograph obtained.**\n\n*Tip: Describe what you see before jumping to a diagnosis. "Multiple loops of dilated bowel with horizontal lines inside them" is more useful than "it looks abnormal."*\n\nOn an upright abdominal X-ray, gas rises to the top of fluid-filled loops, creating air-fluid levels (horizontal lines). The small bowel normally should not exceed 3 cm in diameter.\n\nLook at the bowel gas pattern. Are the loops of bowel dilated? Can you identify air-fluid levels? Is there gas in the colon and rectum?\n\n**What is the difference between small bowel and large bowel on an X-ray, and which do you think is affected here?**`,
    ms_preclinical: `**A 45-year-old female with PMH of appendectomy presents with 2 days of progressive crampy abdominal pain, distension, nausea, and bilious vomiting progressing to feculent. Obstipation for 24 hours. Vitals: HR 105, BP 118/76, T 37.8C. Exam: distended, tympanitic, diffuse tenderness without peritoneal signs, high-pitched tinkling bowel sounds. Labs: WBC 11.2, lactate 1.4, K 3.2, Cl 92. Upright abdominal X-ray obtained.**\n\n*Tip: Be precise. "Dilated loops of small bowel with differential air-fluid levels and paucity of colonic gas" is a much stronger prompt than "something looks wrong."*\n\nApply the 3-6-9 rule: small bowel >3 cm, large bowel >6 cm, cecum >9 cm = abnormally dilated.\n\n**Identify the dilated loops. Are these small bowel or large bowel, and how can you tell? What is the pathophysiology of mechanical bowel obstruction, and why does this patient have hypokalemia and hypochloremia?**`,
    ms_clinical: `**A 45-year-old female with PMH of appendectomy presents with 2 days of progressive crampy abdominal pain, distension, nausea, and bilious vomiting progressing to feculent. Obstipation for 24 hours. Vitals: HR 105, BP 118/76, T 37.8C. Exam: distended, tympanitic, diffuse tenderness without peritoneal signs, high-pitched tinkling bowel sounds. Labs: WBC 11.2, lactate 1.4, K 3.2, Cl 92. Upright abdominal X-ray obtained.**\n\n*Tip: Be precise. "Dilated loops of small bowel with differential air-fluid levels and paucity of colonic gas" is a much stronger prompt than "something looks wrong."*\n\nConfirm the diagnosis on imaging, then plan your management.\n\n**Is this a complete or partial SBO, and how do you determine that? Walk me through your initial management (NPO, NG tube, fluids, electrolyte repletion). What are the indications for surgical intervention vs. continued conservative management? Would you order a Gastrografin challenge?**`,
    resident: `**A 45-year-old female, PMH appendectomy 5 years ago, presents with 2 days of progressive SBO symptoms. Now with feculent vomiting and obstipation x 24h. Vitals: HR 105, BP 118/76, T 37.8C. Exam: distended, tympanitic, diffuse tenderness, no peritoneal signs, high-pitched bowel sounds. Labs: WBC 11.2, lactate 1.4 (normal <2.0), BMP: K 3.2, Cl 92, BUN 28, Cr 1.1. Upright AXR obtained.**\n\n*Tip: Walk me through your decision-making like oral boards. I will push back on gaps in your reasoning.*\n\nYour read: confirm the diagnosis, then outline your management algorithm.\n\n**Interpret this film. Then: (1) What CT findings would indicate strangulation and mandate emergent surgery? (2) This patient has no peritoneal signs and a normal lactate; would you pursue a Gastrografin challenge, and what are the criteria for success vs. failure? (3) If she fails conservative management at 48 hours, what is your operative plan and how do you counsel about recurrence risk?**`,
  },
  'ct-epidural': {
    highschool: `**An 87-year-old woman fell and hit her head. She was brought to the emergency room, and doctors ordered a CT scan of her brain.**\n\nA CT scan is like a very detailed X-ray that takes pictures of slices through the body. On a head CT, bone looks bright white, the brain is gray, and fluid-filled spaces are dark. The brain should look roughly the same on both sides.\n\n*Tip: On CT, bright white means something dense like blood or bone. Dark means air or fluid. When you describe something to the AI, that description is called a prompt. A precise prompt gets a better response.*\n\nLook at this image carefully. Compare the left side and the right side.\n\n**What do you notice that looks different on the two sides? Do you see a bright white area that seems to be pushing things over?**`,
    undergrad: `**An 87-year-old female presents to the ED after a mechanical fall with head strike. She had a brief loss of consciousness, then appeared lucid before rapidly deteriorating. Non-contrast head CT obtained.**\n\nOn a non-contrast head CT, acute blood appears hyperdense (bright white) compared to normal gray brain parenchyma. The brain should be roughly symmetric, and the midline structures (falx cerebri, septum pellucidum) should be centered.\n\n*Tip: Describe the density, shape, and location of any abnormal collection. "Hyperdense biconvex collection in the right temporal region" is a much stronger prompt than "white area on one side."*\n\nLook at both sides of the brain. Identify any abnormal high-density collection. Note its shape and whether it crosses suture lines. Is the midline shifted?\n\n**What is the shape of the abnormal collection, and how does it differ from a subdural hematoma in morphology?**`,
    ms_preclinical: `**An 87-year-old female with PMH of atrial fibrillation on warfarin presents after a mechanical fall with head strike. Witnessed LOC followed by a lucid interval, then rapid decline to GCS 8 (E2V2M4). Vitals: HR 58, BP 188/102, RR 10 (Cushing triad). Non-contrast head CT obtained.**\n\n*Tip: On CT, bright white = dense (blood, bone, contrast). Dark = air or fluid. Be specific with location and morphology in your prompts.*\n\nHead CT systematic read: (1) Scalp and calvarium. (2) Extra-axial spaces. (3) Brain parenchyma. (4) Midline structures. (5) Ventricles. (6) Posterior fossa.\n\n**Describe the finding on CT. What is its shape and what anatomical layer is it in? What artery is classically responsible for epidural hematomas? Explain the pathophysiology of the lucid interval. How does the Monroe-Kellie doctrine explain the rapid clinical deterioration?**`,
    ms_clinical: `**An 87-year-old female with PMH of atrial fibrillation on warfarin presents after a mechanical fall with head strike. Witnessed LOC followed by a lucid interval, then rapid decline to GCS 8 (E2V2M4). Vitals: HR 58, BP 188/102, RR 10 (Cushing triad). Left pupil fixed and dilated. Non-contrast head CT obtained.**\n\n*Tip: On CT, bright white = dense (blood, bone, contrast). Dark = air or fluid. Describe findings precisely for a better teaching response.*\n\nIdentify the finding on CT, assess its severity, and shift to management.\n\n**What is your GCS assessment and what do the individual components tell you? What are the indications for emergent craniotomy? Describe the herniation syndromes, and which one does the fixed dilated left pupil suggest. What is the significance of the Cushing triad?**`,
    resident: `**An 87-year-old female on warfarin (INR 3.2) for AFib presents after mechanical fall. GCS declined from 14 to 8 over 45 minutes. Vitals: HR 52, BP 192/108, RR 10. Left pupil 6mm fixed. Right hemiparesis. Non-contrast head CT shows large right-sided epidural hematoma with 12mm midline shift and early uncal herniation.**\n\n*Tip: Walk me through your decision-making like oral boards. I will challenge gaps in your reasoning.*\n\nThis is a time-critical scenario. Simultaneous resuscitation and surgical planning required.\n\n**Walk me through your ICP management algorithm: osmotic therapy (mannitol vs. hypertonic saline), head of bed positioning, ventilator targets. What is your anticoagulation reversal protocol for warfarin (4-factor PCC vs. FFP, vitamin K dosing)? Discuss surgical timing: does this patient go to OR before or after INR correction? What is the operative approach and what complications are you counseling the family about in an 87-year-old?**`,
  },
  'ct-subdural': {
    highschool: `**An 80-year-old woman came to the hospital after her family noticed she was confused and unsteady. Doctors ordered a CT scan of her brain to look inside.**\n\nA CT scan takes pictures of slices through the head. The brain should look about the same on both sides. Bone appears bright white, brain tissue is gray, and the spaces filled with fluid are very dark.\n\n*Tip: On CT, bright white means something dense like blood or bone. Dark means air or fluid. When you describe something to the AI, that description is called a prompt. A precise prompt gets a better response.*\n\nCompare the two sides of the brain carefully.\n\n**Do you see something extra on one side that should not be there? Does one side look like it is being squeezed?**`,
    undergrad: `**An 80-year-old female presents with progressive confusion, unsteady gait, and left-sided weakness over the past week. PMH includes hypertension and she takes daily aspirin. Non-contrast head CT obtained.**\n\nOn a non-contrast head CT, acute blood is hyperdense (white), subacute blood becomes isodense (same gray as brain), and chronic blood becomes hypodense (dark). The shape of an extra-axial collection helps distinguish its anatomical compartment.\n\n*Tip: Focus on the shape: crescent-shaped collections spread along the brain surface, while lens-shaped collections are confined by dural attachments. A precise description makes a stronger prompt.*\n\nLook at both hemispheres. Identify any abnormal collection. Note its shape, density, and relationship to the falx cerebri.\n\n**Can you identify the crescent-shaped collection? How does its shape differ from an epidural hematoma, and what does that tell you about the anatomical layer it occupies?**`,
    ms_preclinical: `**An 80-year-old female with PMH of HTN, on aspirin 81mg daily, presents with 1 week of progressive headache, confusion, and left-sided weakness. Family reports a fall 3 weeks ago. Exam: GCS 14 (E4V4M6), left pronator drift, left hyperreflexia. Non-contrast head CT obtained.**\n\n*Tip: On CT, bright white = dense (blood, bone, contrast). Dark = air or fluid. Describe findings with anatomical precision for a better teaching response.*\n\nHead CT systematic read: (1) Scalp and calvarium. (2) Extra-axial spaces. (3) Brain parenchyma. (4) Midline structures. (5) Ventricles. (6) Posterior fossa.\n\n**Describe the finding. What is the anatomy of the bridging veins and why are they vulnerable in the elderly? Classify the hematoma density: is this acute, subacute, or chronic? What are the risk factors for subdural hematoma (brain atrophy, anticoagulation, alcoholism)? How does the timing of the fall correlate with the CT appearance?**`,
    ms_clinical: `**An 80-year-old female with PMH of HTN, on aspirin 81mg daily, presents with 1 week of progressive headache, confusion, and left-sided weakness. Family reports a fall 3 weeks ago. Exam: GCS 14 (E4V4M6), left pronator drift, left hyperreflexia. Non-contrast head CT shows a left parafalcine subdural hematoma with 8mm midline shift.**\n\n*Tip: On CT, bright white = dense (blood, bone, contrast). Dark = air or fluid. Describe findings precisely, then shift to management.*\n\nIdentify the finding, classify it, and determine your management plan.\n\n**What are the surgical indications for subdural hematoma (thickness >10mm, midline shift >5mm, GCS drop >2 points)? Does this patient meet criteria for surgery or observation? If surgical, what is the procedure? When would you choose burr hole drainage vs. craniotomy?**`,
    resident: `**An 80-year-old female on aspirin and Plavix (dual antiplatelet for recent coronary stent 4 months ago) presents with subacute decline. GCS 14, left hemiparesis. CT: left parafalcine SDH, mixed density (acute on chronic), 14mm max thickness, 8mm midline shift. No hydrocephalus. Cardiology confirms DES was placed 4 months ago; stopping DAPT carries stent thrombosis risk.**\n\n*Tip: Walk me through your decision-making like oral boards. I will challenge gaps in your reasoning.*\n\nThis case involves competing risks: expanding SDH vs. stent thrombosis.\n\n**Walk me through your antiplatelet reversal protocol: platelet transfusion efficacy for aspirin vs. P2Y12 inhibitors, desmopressin role, and timing of reversal relative to surgery. What is your ICP monitoring plan? Discuss your operative approach: burr hole vs. craniotomy for mixed-density SDH. What is your long-term plan for chronic SDH management (subdural drain duration, repeat imaging protocol, recurrence rate)? How do you navigate the DAPT discussion with cardiology?**`,
  },
  'cxr-pneumoperitoneum': {
    highschool: `**A 71-year-old woman came to the emergency room with sudden, severe belly pain. She feels very sick and her stomach is rigid and tender.**\n\nDoctors ordered an upright chest X-ray. When a patient stands up for a chest X-ray, any free air inside the belly floats upward and collects under the diaphragm (the dome-shaped muscle that separates the chest from the belly).\n\n*Tip: You can ask me to explain anything in simpler terms. Just say "what does that mean?" if I use a word you don't know.*\n\nLook at the very top of the belly area, just below the dome shapes (the diaphragm). Normally you should see the diaphragm sitting right on top of darker organs.\n\n**Do you see a thin dark line under the dome shapes at the top? What do you think that dark line could be, and how might air get inside the belly?**`,
    undergrad: `**A 71-year-old female presents to the ED with acute-onset severe abdominal pain, rigidity, and rebound tenderness. PMH: diverticulosis, hypertension. Vitals: HR 112, BP 98/62, T 38.9C. An upright PA chest radiograph was obtained.**\n\n*Tip: On an upright CXR, free intraperitoneal air rises to the highest point, which is under the diaphragm. "Crescent of lucency under the right hemidiaphragm" is a much stronger prompt than "something looks dark up there."*\n\nOn an upright chest X-ray, the diaphragm normally appears as a smooth dome sitting directly on top of the abdominal organs. If air is free in the peritoneal cavity, it rises and appears as a dark crescent between the diaphragm and the liver or stomach.\n\nLook carefully at both hemidiaphragms. Is there a lucent (dark) line between the diaphragm and the organs below it?\n\n**What causes air to leak into the abdominal cavity? What are the most common causes of bowel perforation?**`,
    ms_preclinical: `**A 71-year-old female with PMH of diverticulosis and HTN presents with acute-onset severe diffuse abdominal pain x 6 hours. Exam: diffuse peritonitis with guarding and rigidity. Vitals: HR 112, BP 98/62, T 38.9C, RR 24. Labs: WBC 18.4 with left shift, lactate 3.8. Upright PA CXR obtained.**\n\n*Tip: Use precise radiologic language. "Free air under the right hemidiaphragm" is a stronger prompt than "something dark at the top."*\n\nSystematic approach: (1) Look under both hemidiaphragms for free air. (2) Assess the lung fields. (3) Check mediastinal contours. Free air under the diaphragm on an upright film is called pneumoperitoneum.\n\n**Identify the finding. What are the causes of pneumoperitoneum (peptic ulcer perforation, diverticular perforation, trauma, iatrogenic)? Describe the peritoneal anatomy: what is the difference between the greater and lesser sac? What is the Rigler sign and when would you see it on a supine film?**`,
    ms_clinical: `**A 71-year-old female with PMH of diverticulosis and HTN presents with acute-onset severe diffuse abdominal pain x 6 hours. Exam: diffuse peritonitis with guarding and rigidity. Vitals: HR 112, BP 98/62, T 38.9C, RR 24. Labs: WBC 18.4 with left shift, lactate 3.8. Upright PA CXR obtained.**\n\n*Tip: Use precise radiologic language. Identify the finding, then shift to management.*\n\nThis is a surgical emergency. Confirm the finding on imaging, then outline your management.\n\n**This patient has free air and peritonitis with hemodynamic instability. What is your initial resuscitation plan? Given her history of diverticulosis, sigmoid perforation is the leading diagnosis. What operation would you perform: Hartmann procedure vs. primary anastomosis? What factors influence this decision (degree of contamination, hemodynamic status, patient comorbidities)?**`,
    resident: `**A 71-year-old female, PMH diverticulosis (known sigmoid disease on prior colonoscopy), HTN, T2DM, BMI 34. Presents with 6 hours of diffuse abdominal pain. Exam: rigid abdomen, diffuse peritonitis. Vitals: HR 112, BP 98/62 (MAP 74), T 38.9C, RR 24, SpO2 94% RA. Labs: WBC 18.4, lactate 3.8, Cr 1.6 (baseline 0.9). Upright CXR obtained. CT abdomen/pelvis shows free air, free fluid, and sigmoid wall thickening with adjacent fat stranding.**\n\n*Tip: Walk me through your decision-making like oral boards. I will push back on gaps in your reasoning.*\n\nThis is Hinchey stage IV (feculent peritonitis). Time to OR is the critical variable.\n\n**Walk me through your first 60 minutes: resuscitation (fluid strategy, vasopressors, broad-spectrum antibiotics per SIS guidelines), OR timing, and operative plan. Hartmann procedure vs. primary anastomosis with diverting loop ileostomy: what does the LADIES trial tell us? Discuss damage control surgery principles if the patient decompensates intraoperatively. What are your sepsis bundle targets?**`,
  },
  'axr-nec': {
    highschool: `**This is an X-ray of a newborn baby who has become very sick. The baby's belly has become swollen and the baby is not tolerating feedings.**\n\nAn X-ray of the belly (abdomen) shows the intestines, which are the long tubes that digest food. In a healthy baby, you would see normal loops of intestine with some gas inside them. The gas appears dark on the X-ray.\n\n*Tip: You can ask me to explain anything. Just say "what does that mean?" if I use a word you don't know.*\n\nLook carefully at the intestines. In a healthy baby, the walls of the intestines should look smooth and thin.\n\n**Do you see any unusual patterns in the intestines? Does the gas pattern look bubbly or frothy in places where it should look smooth?**`,
    undergrad: `**A premature neonate (born at 28 weeks gestational age, now day of life 10) presents with abdominal distension, feeding intolerance, bilious emesis, and bloody stools. Vitals: HR 180, T 36.2C (hypothermia), RR 60. Abdomen is distended and tender with discoloration. An AP abdominal radiograph was obtained.**\n\n*Tip: Describe exactly what you see. "Bubbly lucencies within the bowel wall and branching linear lucencies overlying the liver" is far more useful than "it looks abnormal."*\n\nOn a neonatal abdominal X-ray, look for: (1) bowel gas pattern and distribution, (2) bowel wall integrity, (3) gas where it should not be (in the bowel wall or over the liver), and (4) free air suggesting perforation.\n\nLook for gas where it does not belong: within the bowel wall itself (bubbly or linear pattern) and branching over the liver shadow.\n\n**Can you identify gas in the bowel wall (pneumatosis intestinalis)? Do you see any branching lucencies over the liver that could represent portal venous gas?**`,
    ms_preclinical: `**A 28-week premature neonate (birth weight 1,100g), day of life 10, on enteral feeds with formula. Presents with acute abdominal distension, feeding intolerance, bilious emesis, and hematochezia. Vitals: HR 180, T 36.2C, RR 60, SpO2 88% on nasal cannula. Labs: WBC 4.2 (leukopenia), platelets 62K, CRP 8.4, ABG: pH 7.22, lactate 4.1. AP abdominal radiograph obtained.**\n\n*Tip: Be precise. "Pneumatosis intestinalis with portal venous gas" is a much stronger prompt than "something looks wrong."*\n\nSystematic neonatal AXR read: (1) Bowel gas pattern and distribution. (2) Bowel wall thickness and integrity. (3) Intramural gas (pneumatosis). (4) Portal venous gas. (5) Free air (pneumoperitoneum). (6) Soft tissues.\n\n**Identify the findings. What is the pathophysiology of necrotizing enterocolitis at the cellular level (mucosal ischemia, bacterial translocation, inflammatory cascade)? What are the risk factors (prematurity, formula feeding, perinatal hypoxia)? What is pneumatosis intestinalis and what does it represent histologically?**`,
    ms_clinical: `**A 28-week premature neonate (birth weight 1,100g), day of life 10, on enteral feeds with formula. Presents with acute abdominal distension, feeding intolerance, bilious emesis, and hematochezia. Vitals: HR 180, T 36.2C, RR 60, SpO2 88%. Labs: WBC 4.2, platelets 62K, CRP 8.4, ABG: pH 7.22, lactate 4.1. AP abdominal radiograph obtained showing pneumatosis intestinalis and portal venous gas.**\n\n*Tip: Identify the findings and classify the severity, then shift to management.*\n\nClassify this using the Modified Bell staging system.\n\n**What Modified Bell stage is this patient (Stage I, II, or III)? What are the criteria for each stage? Walk me through medical management (NPO, NGT decompression, broad-spectrum antibiotics, TPN). What finding on AXR mandates surgical intervention (pneumoperitoneum)? What are the other indications for surgical consultation (clinical deterioration, fixed dilated loop, abdominal wall erythema)?**`,
    resident: `**A 28-week premature neonate, DOL 10, birth weight 1,100g, formula-fed. Acute deterioration with distension, hematochezia, and hemodynamic instability requiring pressors. Labs: WBC 4.2 (bandemia), platelets 62K, CRP 8.4, ABG: pH 7.22, lactate 4.1, base deficit -12. Serial AXRs show progressive pneumatosis intestinalis, portal venous gas, and now a fixed dilated loop in the RLQ that has not changed position over 12 hours.**\n\n*Tip: Walk me through your decision-making like oral boards. I will challenge gaps in your reasoning.*\n\nThis is Modified Bell Stage IIIB (advanced NEC with intestinal perforation or clinical deterioration despite maximal medical therapy).\n\n**Walk me through your serial AXR monitoring protocol: what are you looking for on each film and how frequently? The fixed dilated loop is concerning: why, and does it mandate surgery? Discuss the surgical options: peritoneal drain (penrose drain) vs. exploratory laparotomy. When do you choose each? What are the long-term complications (short bowel syndrome, stricture formation, neurodevelopmental outcomes) and how do you counsel the family?**`,
  },
  'xr-colles': {
    highschool: `**An adult tripped and fell, landing on an outstretched hand. Their wrist is now very swollen and painful, and it looks bent at an odd angle. The doctor ordered an X-ray of the wrist.**\n\nOn an X-ray, bones appear bright white and soft tissues are gray. The two main bones in the forearm are the radius (on the thumb side) and the ulna (on the pinky side). They connect to the small wrist bones at the bottom of the image.\n\n*Tip: You can ask me to explain anything. Just say "what does that mean?" if I use a word you don't know.*\n\nLook at the bone on the thumb side near the wrist. Follow it down toward the wrist joint.\n\n**Can you see where the bone looks broken? Does one part of the bone look like it is pushed backward compared to the rest?**`,
    undergrad: `**An adult presents to the ED after a fall onto an outstretched hand (FOOSH injury). The wrist is swollen with a visible deformity. PA and lateral wrist radiographs were obtained.**\n\n*Tip: "Transverse fracture of the distal radius with dorsal displacement and angulation" is a much stronger prompt than "the bone looks broken."*\n\nOn a lateral wrist X-ray, the distal radius should have a slight volar (palmar) tilt of about 11 degrees. On the PA view, the radial articular surface normally has about 22 degrees of inclination. A fracture that disrupts these angles produces visible deformity.\n\nLook at the distal radius on both views. Identify the fracture line. On the lateral view, note the direction of displacement.\n\n**Can you identify the fracture line? Describe the displacement and angulation you see. What is the "dinner fork" deformity and why does it occur with this type of fracture?**`,
    ms_preclinical: `**An adult presents after a fall onto an outstretched hand (FOOSH). Exam: dorsal wrist deformity ("dinner fork"), tenderness over the distal radius, limited ROM. Neurovascularly intact distally. PA and lateral wrist radiographs obtained.**\n\n*Tip: Use precise orthopedic language. "Distal radius fracture with 25 degrees of dorsal tilt and 5mm of shortening" is a much stronger prompt than "the wrist is broken."*\n\nOn the PA view, assess: radial inclination (normal ~22 degrees), radial height (normal ~11mm), and articular congruity. On the lateral view, assess: volar tilt (normal ~11 degrees volar; dorsal tilt = abnormal).\n\n**Describe the fracture. What is the mechanism (FOOSH)? Differentiate Colles fracture (dorsal displacement) from Smith fracture (volar displacement) and Barton fracture (rim fracture with subluxation). What is the relevant radiocarpal joint anatomy? Which nerve is at risk and why (median nerve and carpal tunnel)?**`,
    ms_clinical: `**An adult presents after a FOOSH injury. Exam: dorsal wrist deformity, swelling, and tenderness. Neurovascularly intact. PA and lateral wrist X-rays show a distal radius fracture with dorsal displacement and angulation, 3mm of radial shortening, and no intra-articular extension.**\n\n*Tip: Identify the fracture, classify it, then plan management.*\n\nAssess the fracture on both views and determine your management plan.\n\n**Describe your reduction technique for a Colles fracture (hematoma block, traction, manipulation). What are the indications for ORIF vs. closed reduction and casting (dorsal tilt >20 degrees, radial shortening >3mm, intra-articular step-off >2mm)? What is your neurovascular exam checklist? How do you assess for and monitor compartment syndrome?**`,
    resident: `**An adult, PMH osteoporosis, presents after a ground-level FOOSH. X-rays: comminuted distal radius fracture with 25 degrees dorsal tilt, 5mm radial shortening, 2mm intra-articular step-off involving the scaphoid fossa. Ulnar styloid avulsion fracture present. DRUJ stability questionable on exam. Neurovascularly intact.**\n\n*Tip: Walk me through your decision-making like oral boards. I will challenge gaps in your reasoning.*\n\nThis fracture meets multiple operative criteria.\n\n**Walk me through the operative criteria: dorsal tilt >20 degrees, radial shortening >3mm, intra-articular step-off >2mm. This patient meets all three. What is your preferred fixation (volar locking plate vs. external fixation vs. fragment-specific fixation) and why? How does the ulnar styloid fracture and potential DRUJ instability change your plan? Discuss late complications: EPL tendon rupture (and its mechanism from the Lister tubercle), malunion, post-traumatic arthritis, and CRPS. What is your post-operative rehab protocol?**`,
  },
};

function welcomeMessage(level: LearnerLevel, studyId?: string): string {
  if (studyId && CXR_WELCOME_MESSAGES[studyId]) {
    const base = CXR_WELCOME_MESSAGES[studyId][level] || CXR_WELCOME_MESSAGES[studyId].ms_preclinical;
    const tipToInject = studyId.startsWith('ct-') ? CT_TIP : CXR_TIP;
    return base.replace(/\*Tip:[^*]+\*/, tipToInject);
  }

  if (level === 'highschool') {
    return `**Case: 72-year-old woman with memory problems.**\n\nFor the past 6 months she has been forgetting words and getting lost in places she knows well. She also has an irregular heartbeat, high blood pressure, and diabetes. Her doctor ordered a brain scan (MRI) to figure out what is going on.\n\n${MRI_TIP}\n\n---\n\nYou are looking at a brain MRI. This is a special type of picture that lets doctors see inside the brain without surgery. You are on the FLAIR view, which is good at showing areas of damage.\n\nScroll through the slices and look for anything that seems different between the left and right sides of the brain. When you spot something, capture it with the camera.\n\n**What do you think could cause someone to lose their memory?**`;
  }

  if (level === 'undergrad') {
    return `**Case: 72-year-old female, progressive memory decline.**\n\n6-month history of word-finding difficulty and spatial disorientation. PMH: atrial fibrillation (irregular heart rhythm that can cause blood clots), hypertension, type 2 diabetes. Brain MRI ordered to evaluate for dementia.\n\n${MRI_TIP}\n\n---\n\nYou are starting on the FLAIR sequence, which suppresses cerebrospinal fluid signal and makes areas of edema or gliosis appear bright. This is the go-to sequence for spotting white matter lesions and infarcts.\n\nScroll through the slices. Look for asymmetry between hemispheres, bright signal where it should not be, or changes in ventricle size.\n\n**Given her risk factors (atrial fibrillation, hypertension, diabetes), what vascular pathology might explain her symptoms?**`;
  }

  if (level === 'resident') {
    return `**Case: 72F, progressive cognitive decline x 6 months.**\n\nPresenting complaint: word-finding difficulty, topographic disorientation. PMH: atrial fibrillation (on apixaban), HTN (on lisinopril), T2DM (A1c 7.8). No acute focal deficits on exam. MMSE 22/30. MRI brain ordered to evaluate for vascular vs. neurodegenerative etiology.\n\n${MRI_TIP}\n\n---\n\nYou are on FLAIR. Your systematic approach: (1) Survey for territorial infarcts and their vascular distribution. (2) Grade periventricular and deep white matter hyperintensities (Fazekas scale). (3) Assess for volume loss patterns (global vs. focal, symmetric vs. asymmetric). (4) Cross-reference DWI for acute vs. chronic lesions.\n\nScroll through, identify all findings, then capture.\n\n**What is your differential for progressive cognitive decline with these vascular risk factors, and how would you use the MRI sequences to distinguish vascular cognitive impairment from Alzheimer disease?**`;
  }

  if (level === 'ms_clinical') {
    return `**Case: 72-year-old female, progressive memory decline.**\n\n6-month history of word-finding difficulty and getting lost in familiar places. PMH: atrial fibrillation, hypertension, type 2 diabetes. MMSE 22/30. Brain MRI ordered.\n\n${MRI_TIP}\n\n---\n\nSystematic MRI read: (1) Survey for territorial infarcts. (2) Grade white matter disease. (3) Assess volume loss patterns. (4) Cross-reference DWI for acute vs. chronic.\n\nScroll through, identify all findings, then capture.\n\n**What is your differential for this presentation? How do you distinguish vascular cognitive impairment from Alzheimer disease on imaging? What is this patient's CHA2DS2-VASc score and is anticoagulation adequate?**`;
  }

  return `**Case: 72-year-old female, progressive memory decline.**\n\n6-month history of word-finding difficulty and getting lost in familiar places. Past medical history: atrial fibrillation, hypertension, type 2 diabetes. Brain MRI ordered to rule out dementia.\n\n${MRI_TIP}\n\n---\n\nYou are starting on the FLAIR sequence. Scroll through the slices, and when you see something that catches your eye, capture it with the camera and tell me what you see.\n\n**What structures can you identify on this slice? Do you notice any areas where the signal intensity looks different between the two hemispheres? What are you expecting to find given this patient's history?**`;
}

function getInitialSuggestions(level: LearnerLevel, hasImage: boolean, studyId?: string): string[] {
  if (isCxrLikeCase(studyId)) {
    return (hasImage ? CXR_SUGGESTIONS_WITH_IMAGE : CXR_SUGGESTIONS_NO_IMAGE)[level] || [];
  }
  return (hasImage ? SUGGESTIONS_WITH_IMAGE : SUGGESTIONS_NO_IMAGE)[level] || [];
}

export const radiology: Domain = {
  key: 'radiology',
  label: 'Radiology',
  artifactHints: {
    showWindowLevel: true,
    showSeriesSelector: true,
    showSegmentation: true,
  },
  welcomeMessage,
  getInitialSuggestions,
  contextLabel: (dicomModality: string) => `Radiology (${dicomModality})`,
  captureLabel: () => 'MRI series',
};
