/** Build card-only display derivatives; never rewrite a canonical case asset. */
import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { listBuiltinCasePackages } from '../src/data/caseRegistry';

const root = fileURLToPath(new URL('../', import.meta.url));
const directory = path.join(root, 'public/thumbnails/library');
const digest = (bytes: Uint8Array) => createHash('sha256').update(bytes).digest('hex');
const cases = await listBuiltinCasePackages();
const index: Record<string, { sourceSha256: string; src: string; width: number; height: number }> = {};
const records = [];
const outputNames = new Set<string>();
await mkdir(directory, { recursive: true });

for (const casePackage of cases) {
  const source = casePackage.preview;
  if (!source.src.startsWith('/images/') || source.src.includes('..')) {
    throw new Error(`Expected a bundled image for ${casePackage.id}`);
  }
  const original = await readFile(path.join(root, 'public', source.src));
  if (digest(original) !== source.sha256) throw new Error(`Source hash mismatch: ${casePackage.id}`);
  const metadata = await sharp(original).metadata();
  if ((metadata.pages ?? 1) !== 1 || !['jpeg', 'png', 'webp'].includes(metadata.format)) {
    throw new Error(`Review the new preview format before generating: ${casePackage.id}`);
  }
  const { data, info } = await sharp(original)
    .autoOrient()
    .withIccProfile('srgb', { attach: false })
    .resize({ width: 960, height: 400, fit: 'inside', withoutEnlargement: true })
    .webp({ quality: 82, effort: 6 })
    .toBuffer({ resolveWithObject: true });
  const sha256 = digest(data);
  const filename = `${casePackage.id}-${sha256.slice(0, 16)}.webp`;
  outputNames.add(filename);
  await writeFile(path.join(directory, filename), data);
  index[source.src] = {
    sourceSha256: source.sha256,
    src: `/thumbnails/library/${filename}`,
    width: info.width,
    height: info.height,
  };
  records.push({
    caseId: casePackage.id,
    title: casePackage.title,
    source: { src: source.src, sha256: source.sha256, bytes: original.length },
    thumbnail: { src: index[source.src].src, sha256, bytes: data.length, width: info.width, height: info.height },
    attribution: casePackage.provenance.attribution,
    sourceName: casePackage.provenance.sourceName,
    sourceUrl: casePackage.provenance.sourceUrl,
    license: casePackage.provenance.license,
  });
}

await writeFile(path.join(root, 'src/data/libraryThumbnails.generated.ts'),
  '// Generated by npm run thumbnails:generate. Card display only; canonical assets stay unchanged.\n'
  + 'export const LIBRARY_THUMBNAILS = ' + JSON.stringify(index, null, 2) + ' as const;\n');
await writeFile(path.join(directory, 'NOTICE.json'), JSON.stringify({
  description: 'Library card display derivatives of the listed canonical teaching assets. Original attribution and licenses apply. Open a case to inspect the original image.',
  transformation: 'Aspect-preserving downsize inside 960 × 400 without enlargement or cropping, orientation normalization, sRGB conversion, metadata removal, WebP quality 82.',
  encoder: { sharp: sharp.versions.sharp, vips: sharp.versions.vips, webp: sharp.versions.webp },
  records,
}, null, 2) + '\n');

const escapeHtml = (value: string) => value.replace(/[&<>"']/g, character => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
}[character]!));
await writeFile(path.join(root, 'public/image-credits.html'), `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Image credits · CaseAttend</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#090c12;color:#dce3ef;font:16px/1.65 system-ui,sans-serif}
main{max-width:920px;margin:auto;padding:32px 24px 64px}a{color:#a6baff;text-underline-offset:4px}
a:hover{color:white}a:focus-visible{outline:2px solid #a6baff;outline-offset:5px;border-radius:2px}
nav a{display:inline-flex;align-items:center;min-height:44px}h1{font-size:clamp(2rem,5vw,3rem);line-height:1.15;letter-spacing:-.035em;margin:32px 0 16px}
h2{font-size:1.15rem;line-height:1.4;color:#f2f5fa;margin:0 0 12px}p{margin:0 0 12px;color:#b6c0d0}
.intro{max-width:720px;margin-bottom:36px}ol{padding:0;list-style:none;display:grid;gap:16px}
li{border:1px solid #273142;background:#101722;border-radius:16px;padding:24px;overflow-wrap:anywhere}
li p:last-child{margin:0}footer{margin-top:32px;font-size:.9rem}
</style></head><body><main>
<nav aria-label="Back to CaseAttend"><a href="/">← Back to cases</a></nav>
<h1>Image credits</h1>
<p class="intro">These teaching images are shared by the creators and collections credited below. Each image retains its listed license. Library cards show smaller copies; opening a case loads the original teaching image.</p>
<ol>${records.map(record => `<li id="${escapeHtml(record.caseId)}"><h2>${escapeHtml(record.title)}</h2>
<p>${escapeHtml(record.attribution)}</p>
<p>${record.sourceUrl ? `<a href="${escapeHtml(record.sourceUrl)}">${escapeHtml(record.sourceName)}</a>` : escapeHtml(record.sourceName)} · ${record.license.url ? `<a href="${escapeHtml(record.license.url)}">${escapeHtml(record.license.name)}</a>` : escapeHtml(record.license.name)}</p></li>`).join('\n')}</ol>
<footer><a href="/thumbnails/library/NOTICE.json">Download attribution and thumbnail provenance</a></footer>
</main></body></html>\n`);

// Remove only obsolete outputs in this dedicated generated directory.
for (const filename of await readdir(directory)) {
  if (/^[a-z0-9-]+-[a-f0-9]{16}\.webp$/.test(filename) && !outputNames.has(filename)) {
    await unlink(path.join(directory, filename));
  }
}
for (const [label, group] of [['First 12', records.slice(0, 12)], ['All cases', records]] as const) {
  const sourceBytes = group.reduce((total, entry) => total + entry.source.bytes, 0);
  const thumbnailBytes = group.reduce((total, entry) => total + entry.thumbnail.bytes, 0);
  console.log(`${label}: ${sourceBytes} → ${thumbnailBytes} bytes (${(100 * (1 - thumbnailBytes / sourceBytes)).toFixed(1)}% smaller)`);
}
