import { readFile, writeFile } from 'node:fs/promises';
import { listBuiltinCasePackages } from '../src/data/caseRegistry';
import { requireLessonPlanForCase } from '../src/data/lessonRegistry';
import { starterEntryFor } from './introCache/starterIndex';

const checkOnly = process.argv.includes('--check');
const entries: Record<string, readonly [string, string]> = {};
const cases = await listBuiltinCasePackages();
for (const casePackage of cases) {
  const lesson = await requireLessonPlanForCase(casePackage);
  let payload: unknown;
  try {
    payload = JSON.parse(await readFile(new URL(`../public/intro-cache/${casePackage.id}.json`, import.meta.url), 'utf8'));
  } catch (error) {
    if (error instanceof SyntaxError || (error as NodeJS.ErrnoException).code === 'ENOENT') continue;
    throw error;
  }
  const entry = starterEntryFor(casePackage, lesson.manifest.sha256, payload);
  if (entry) entries[casePackage.id] = entry;
}

const output = `// Generated by npm run starters:generate. No answer text is bundled here.\n// Values are [case package SHA-256, resolved lesson SHA-256].\nexport const BUILTIN_STARTERS: Readonly<Record<string, readonly [string, string]>> = ${JSON.stringify(entries, null, 2)};\n`;
const destination = new URL('../src/data/builtinStarters.generated.ts', import.meta.url);
if (checkOnly) {
  const existing = await readFile(destination, 'utf8').catch(error => {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return '';
    throw error;
  });
  if (existing !== output) throw new Error('Starter availability is out of date. Run npm run starters:generate and commit the updated index.');
} else {
  await writeFile(destination, output);
}
console.log(`${checkOnly ? 'Checked' : 'Indexed'} ${Object.keys(entries).length} of ${cases.length} built-in cases with current, approved starter answers.`);
