// Generated by npm run thumbnails:generate. Card display only; canonical assets stay unchanged.
export const LIBRARY_THUMBNAILS = {
  "/images/sub-1/FLAIR/14.png": {
    "sourceSha256": "f2e26280e49ef4941f50bd116dad3937b9343dbc12f4c7e21a30531abaeaf82c",
    "src": "/thumbnails/library/local-study-sub1-083aaaef579a50ec.webp",
    "width": 256,
    "height": 256
  },
  "/images/patho-1/HE_10x/1.webp": {
    "sourceSha256": "1231f129c548e0e3482b160354fc9cbfea4ddbdd3bf4c76c74adfbfa777dc32a",
    "src": "/thumbnails/library/patho-study-breast-0e3dc67739921976.webp",
    "width": 400,
    "height": 400
  },
  "/images/cxr-pneumothorax/1.jpg": {
    "sourceSha256": "fe79c23752a7f32c5e8748726ca596ab94d9f4a5a878f768cd4d1d9eaa2bc7cd",
    "src": "/thumbnails/library/cxr-pneumothorax-3ff3b17a8d4d3bae.webp",
    "width": 311,
    "height": 400
  },
  "/images/cxr-pneumonia/1.jpg": {
    "sourceSha256": "cae983ca0ed90b161ff55a49915f563939cdee792efcc98788e5749ae75e6f76",
    "src": "/thumbnails/library/cxr-pneumonia-43639f3220b05561.webp",
    "width": 503,
    "height": 400
  },
  "/images/cxr-chf/1.jpg": {
    "sourceSha256": "24987bed716d82b6750cfd736c47604a29bf8acedc11ff6120768e5673a3b0b8",
    "src": "/thumbnails/library/cxr-chf-bd53044bf58c65b8.webp",
    "width": 404,
    "height": 400
  },
  "/images/cxr-effusion/1.jpg": {
    "sourceSha256": "9b5505fb0a022a2503b8e07ddee9f1db4655010a9343a7ccab87f7b979e8f30b",
    "src": "/thumbnails/library/cxr-effusion-75781b623d136815.webp",
    "width": 474,
    "height": 400
  },
  "/images/axr-sbo/1.jpg": {
    "sourceSha256": "3ca32774782fec475335482d7284932b0c0a412d19f0d7070dc1dfaad1339e42",
    "src": "/thumbnails/library/axr-sbo-a097a9e2a51b7a73.webp",
    "width": 339,
    "height": 400
  },
  "/images/ct-epidural/1.jpg": {
    "sourceSha256": "ec2c603b32b60465f216fbc8b99a9eeaa95097befc674acd8ca7509c688332d7",
    "src": "/thumbnails/library/ct-epidural-468f51c38b0fad90.webp",
    "width": 449,
    "height": 400
  },
  "/images/ct-subdural/1.jpg": {
    "sourceSha256": "eacc993a674c130a48343bff4068da94ad8253555e5f6023fe5184de0bff061f",
    "src": "/thumbnails/library/ct-subdural-f9fd0d6a9b52ecde.webp",
    "width": 688,
    "height": 400
  },
  "/images/cxr-pneumoperitoneum/1.jpg": {
    "sourceSha256": "513d73d4915b8a14055e89a5af0115f43c53de24e3f0fb8d43f506cc63bf42ed",
    "src": "/thumbnails/library/cxr-pneumoperitoneum-997b2f152644aaa3.webp",
    "width": 430,
    "height": 400
  },
  "/images/axr-nec/1.jpg": {
    "sourceSha256": "cb038906e0c5dfe5e15929127216d1cfb2430aaa54a7d7e862d6021be52ef41f",
    "src": "/thumbnails/library/axr-nec-20a910a15cec1aed.webp",
    "width": 499,
    "height": 400
  },
  "/images/xr-colles/1.jpg": {
    "sourceSha256": "b1216679cdcf446e9c023ea6493831162e8f8a9f82e4e4ef47d8234e81d9ba94",
    "src": "/thumbnails/library/xr-colles-01de6304414b3c2e.webp",
    "width": 362,
    "height": 400
  },
  "/images/derm-melanoma/1.jpg": {
    "sourceSha256": "426662261a6ff73f4122cad0604df95019b14395b74600eafc8d80019e45f14d",
    "src": "/thumbnails/library/derm-melanoma-79b13c1d8d2907d8.webp",
    "width": 575,
    "height": 400
  },
  "/images/derm-bcc/1.jpg": {
    "sourceSha256": "a790c080ea607f3a512bfb607030f5e173d44050f3ffa100f332ce2ad244ee2b",
    "src": "/thumbnails/library/derm-bcc-1e9bee7a37a04121.webp",
    "width": 397,
    "height": 400
  },
  "/images/derm-sebk/1.jpg": {
    "sourceSha256": "e1b31d6a8336da4a0032dec03e6bba192ea9f01a0948c1b2426b01bc5af8e5df",
    "src": "/thumbnails/library/derm-sebk-df95eb9520e7a8b2.webp",
    "width": 458,
    "height": 400
  },
  "/images/ultrasound-pocus/us-appendix-normal.jpg": {
    "sourceSha256": "a753ee04904c37c994f88da6a7ae38641bbcaa753b66501aa4913fbb7e824d88",
    "src": "/thumbnails/library/us-appendix-normal-7f91bf3fad7252e2.webp",
    "width": 343,
    "height": 232
  },
  "/images/ultrasound-pocus/us-cholecystitis.jpg": {
    "sourceSha256": "3f41f1fb8ac2841b183778c4988770b2e588212962b32a08b62cd57e581daad9",
    "src": "/thumbnails/library/us-cholecystitis-67c1cc4420e5b19e.webp",
    "width": 471,
    "height": 400
  },
  "/images/ultrasound-pocus/us-renal-diabetic.jpg": {
    "sourceSha256": "0b983378960f1cfb0cfcc79419d99d36d7a6ac18bdd22f91aa43c91a73b1f29f",
    "src": "/thumbnails/library/us-renal-diabetic-433cfbf5af762c7f.webp",
    "width": 395,
    "height": 400
  },
  "/images/ultrasound-pocus/us-lung-blines.png": {
    "sourceSha256": "ab76ad0af4c188d5bc2961e62a577812e24f388d069ed57c3ac04b70ebb71976",
    "src": "/thumbnails/library/us-lung-blines-ce38258bb851ca80.webp",
    "width": 435,
    "height": 362
  },
  "/images/ultrasound-pocus/us-plax-mmode.jpg": {
    "sourceSha256": "1aeaf07e59ffeeb203f16c509a9c5a6c407687f717317707b26bd8672278c384",
    "src": "/thumbnails/library/us-plax-mmode-140463352b7f45b0.webp",
    "width": 586,
    "height": 400
  },
  "/images/ultrasound-pocus/us-echo-4chamber.jpg": {
    "sourceSha256": "676abf601b5ed54a9a76cabeb4b2828a7b4fd46fb672b388366d783433ca1d4d",
    "src": "/thumbnails/library/us-echo-4chamber-241abd4d7d7a2261.webp",
    "width": 586,
    "height": 400
  },
  "/images/ultrasound-pocus/us-echo-asd.jpg": {
    "sourceSha256": "99816c9f6b6410cbc047105e229ac0d8515ebd16c520a062e1362a1489367f64",
    "src": "/thumbnails/library/us-echo-asd-97dbc53880ed1c7a.webp",
    "width": 586,
    "height": 400
  },
  "/images/ultrasound-pocus/us-echo-vsd.jpg": {
    "sourceSha256": "6587b70a52c29da4d7dbeb48dd2c84a99460c95e0ffc641a848ef11104e8e26e",
    "src": "/thumbnails/library/us-echo-vsd-801634a4d22eb79b.webp",
    "width": 586,
    "height": 400
  },
  "/images/ecg-signals/ecg-afib.jpg": {
    "sourceSha256": "fbe2549e9a581601d9f40e9160bac275df298933f544b6653c896901b5a6bd02",
    "src": "/thumbnails/library/ecg-afib-319d6ae06f866a51.webp",
    "width": 567,
    "height": 400
  },
  "/images/ecg-signals/ecg-cvp.jpg": {
    "sourceSha256": "b2773acabb33e10882646f1619cd1ab951fb8e560154a363ee8fb4f6f94488ce",
    "src": "/thumbnails/library/ecg-cvp-6d67a39e4ebe68c0.webp",
    "width": 867,
    "height": 400
  },
  "/images/chest-radiograph-open/cxr-tb-cavitary.jpg": {
    "sourceSha256": "9c6fb83021e235d3e3e404019e4fb90692f6b847486d9d094daf32c96d6c5ff4",
    "src": "/thumbnails/library/cxr-tb-cavitary-3fa792243c74a09f.webp",
    "width": 517,
    "height": 400
  },
  "/images/chest-radiograph-open/cxr-sars.jpg": {
    "sourceSha256": "f2f8096a25aac0b33cd66be6b7a3189466f61f7c7c60ce054c7acda2b4f57610",
    "src": "/thumbnails/library/cxr-sars-aab70db9f192ae99.webp",
    "width": 442,
    "height": 400
  },
  "/images/chest-radiograph-open/cxr-hantavirus.jpg": {
    "sourceSha256": "c4ab9c531a16781ddfcf1f3114c0ed842e7c61021cb6b07c826a156090fd0e65",
    "src": "/thumbnails/library/cxr-hantavirus-9c1908dda4fc6a8e.webp",
    "width": 602,
    "height": 400
  },
  "/images/chest-radiograph-open/cxr-histoplasmosis.jpg": {
    "sourceSha256": "b6d86140c440c02104d008c7c323ab511c02edd55646b924c6d233dabc32b7be",
    "src": "/thumbnails/library/cxr-histoplasmosis-449de03247a31cba.webp",
    "width": 419,
    "height": 400
  },
  "/images/chest-radiograph-open/cxr-fibrothorax.jpg": {
    "sourceSha256": "9a889f6c4ad233038780a3d34f1fe706e2f87848fafbe69d174c530ad85cc5a5",
    "src": "/thumbnails/library/cxr-fibrothorax-1a6d4c5a169a8903.webp",
    "width": 406,
    "height": 400
  },
  "/images/chest-radiograph-open/cxr-lung-mass.jpg": {
    "sourceSha256": "330953bc2237aeb72a9862d5cc6d78a05f5664ad2a82da3114790d140ed1f3fd",
    "src": "/thumbnails/library/cxr-lung-mass-01318800f047b440.webp",
    "width": 400,
    "height": 400
  },
  "/images/ophthalmology-fundus/fundus-normal.jpg": {
    "sourceSha256": "6da1df2020cc1fdde88955822c82d69141e30d37cace80760c8c82328ee91285",
    "src": "/thumbnails/library/fundus-normal-5b1e504c2a9d8511.webp",
    "width": 571,
    "height": 400
  },
  "/images/ophthalmology-fundus/fundus-background-dr.jpg": {
    "sourceSha256": "b14c70ceffad9fa592ec6e340b4a08b47184f70ddc6e5708ba3495f2916196f6",
    "src": "/thumbnails/library/fundus-background-dr-7edfc42bcfa1e291.webp",
    "width": 600,
    "height": 400
  },
  "/images/ophthalmology-fundus/fundus-proliferative-dr.jpg": {
    "sourceSha256": "389469b439973952b4532d4ef662ee1215434ea96bb8c912ded55621a5efabae",
    "src": "/thumbnails/library/fundus-proliferative-dr-1b90e83c1dce8858.webp",
    "width": 611,
    "height": 400
  },
  "/images/ophthalmology-fundus/fundus-macular-edema.jpg": {
    "sourceSha256": "93fbe9306cd072e0b5ff80ab3d735ce56365c48e64fcd0a639c1907330f22f9e",
    "src": "/thumbnails/library/fundus-macular-edema-7a2723ac83ac7d69.webp",
    "width": 600,
    "height": 400
  },
  "/images/ophthalmology-fundus/fundus-amd.jpg": {
    "sourceSha256": "6a7843639363ac00db2ee0f5ba5dce66ac2b4f75948cc6b9a0e9b8f7121080e6",
    "src": "/thumbnails/library/fundus-amd-81c9708bd74d1ba5.webp",
    "width": 400,
    "height": 343
  },
  "/images/ophthalmology-fundus/fundus-cmv-retinitis.jpg": {
    "sourceSha256": "d92d37e452b620e1f23e27fa3c4cf225f0158fb9dee49d5d2ded58a19f78bd7d",
    "src": "/thumbnails/library/fundus-cmv-retinitis-82ca147b3dbcd283.webp",
    "width": 600,
    "height": 400
  },
  "/images/ophthalmology-fundus/fundus-retinal-detachment.jpg": {
    "sourceSha256": "e5de317dd24a5d9b1b373964a42696e907eedb5186652b2d7f6c0461d6526f2f",
    "src": "/thumbnails/library/fundus-retinal-detachment-434e543412a26884.webp",
    "width": 504,
    "height": 386
  },
  "/images/mri-neuro-open/mri-posterior-fossa.jpg": {
    "sourceSha256": "40dbca7cf38173760da8c21e9923ba427d944b5257ed264834fc52daa88fd76b",
    "src": "/thumbnails/library/mri-posterior-fossa-806cf21bbca8e492.webp",
    "width": 401,
    "height": 400
  },
  "/images/mri-neuro-open/mri-white-matter.jpg": {
    "sourceSha256": "fb11282328ad7d61012e60f973c20a8e824883079a2712244cb9d76762d2932f",
    "src": "/thumbnails/library/mri-white-matter-adf511e582befe14.webp",
    "width": 327,
    "height": 400
  },
  "/images/pathology-micro-open/path-breast-duct.jpg": {
    "sourceSha256": "bcfa06dd36b1e24b866ac628f4f05e06175e24a889d14eefc306ab2edda9877c",
    "src": "/thumbnails/library/path-breast-duct-2846dfb4a53f15fc.webp",
    "width": 600,
    "height": 400
  },
  "/images/pathology-micro-open/path-prostate.jpg": {
    "sourceSha256": "6dbaaf2aa48939649ebd0a76b106bce6c8784aa8c95c56ff06c9aa4d64bf2c63",
    "src": "/thumbnails/library/path-prostate-00b09d5761865c58.webp",
    "width": 549,
    "height": 400
  },
  "/images/pathology-micro-open/path-afb-sputum.png": {
    "sourceSha256": "3d817e35cfae818231202bf2020818534aa5575a0507bcf80454fa64b80a9025",
    "src": "/thumbnails/library/path-afb-sputum-22b20dbd18e2ef3b.webp",
    "width": 400,
    "height": 400
  },
  "/images/pathology-micro-open/path-malaria-falciparum.png": {
    "sourceSha256": "fdcd68a07c31eb5d1aed5bf41d46b5348391bc58d912d11c0f5978473cd0089e",
    "src": "/thumbnails/library/path-malaria-falciparum-8345509adbed8473.webp",
    "width": 597,
    "height": 400
  },
  "/images/pathology-micro-open/path-malaria-vivax.png": {
    "sourceSha256": "ff5c07f8176bf7f01f073bf1ce2facc3cbca9049efbf693e41c42efbd96bb270",
    "src": "/thumbnails/library/path-malaria-vivax-f6c567fdad914b73.webp",
    "width": 594,
    "height": 400
  },
  "/images/pathology-micro-open/path-giardia.jpg": {
    "sourceSha256": "ee4bafa5b278a09a2d6bb16723d7487b62339887154fc76328696f3fa39f6cfe",
    "src": "/thumbnails/library/path-giardia-d3873409b399fe9a.webp",
    "width": 340,
    "height": 400
  },
  "/images/pathology-micro-open/path-reye-liver.jpg": {
    "sourceSha256": "105fb192f06af1e453078082db4587377f4bfbbf3979488b12d05d1707432072",
    "src": "/thumbnails/library/path-reye-liver-ea0c9ca5c5659a16.webp",
    "width": 605,
    "height": 400
  },
  "/images/pathology-micro-open/path-schistosoma.jpg": {
    "sourceSha256": "fe6c850ad833d083139c3ad76bc46d4095956cba03a921915c7743310a92a82a",
    "src": "/thumbnails/library/path-schistosoma-9939f5b75b8fa456.webp",
    "width": 599,
    "height": 400
  }
} as const;
